constraint_setting(
    name = "mode",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "debug",
    constraint_setting = ":mode",
    visibility = ["PUBLIC"],
)

constraint_value(
    name = "release",
    constraint_setting = ":mode",
    visibility = ["PUBLIC"],
)

