[platform.linux-x86_64]
target = "x86_64-unknown-linux-gnu"

[platform.linux-arm64]
target = "aarch64-unknown-linux-gnu"

[platform.macos-x86_64]
target = "x86_64-apple-darwin"

[platform.macos-arm64]
target = "aarch64-apple-darwin"

[platform.windows-msvc]
target = "x86_64-pc-windows-msvc"

[platform.windows-gnu]
target = "x86_64-pc-windows-gnu"
