[package]
# Pseudo-package whose dependencies are imported and buckified
name = "project"
version = "0.0.0"
edition = "2021"
publish = false

# List of packages to be imported, with version constraints, features
# and all options Cargo supports.
[dependencies]
once_cell = "1.4"
